In [2]:
import numpy as np

In [8]:
a = np.array([1 ,2, "3" , 4.5])
print(a)


['1' '2' '3' '4.5']


In [6]:
matrix = np.array([[1,2,3] ,[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [13]:
np.zeros((2, 4)) ## create the 2*4 matrix



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 4))   ## create 3*4 matrix twice 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.zeros((1))

array([0.])

In [16]:
np.ones((1))

array([1.])

In [ ]:
np.ones((6,3)) ## same as the zeros 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((3, 2) , 5)    ##  3*2 matrix full of 5 

array([[5, 5],
       [5, 5],
       [5, 5]])

In [ ]:
np.ones((4 ,2 ,3 , 5))   ## in the 4D arrays it will give 3*5 matrix 4*2 times
np.ones((2 ,3 ,4 , 5,6))  ## in the 5D arrays it will give 5*6 matrix 2*3*4 times

In [ ]:
np.arange(1 , 11 , 2) ## same as like slice

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1 , 10  , 4)   ## give equal distace of 4 

array([ 1.,  4.,  7., 10.])

In [ ]:
np.eye(3)   ## give the indiacal matrix of order of 4  and the dtypes of numeber is float64


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.array([1 ,2 ,3 ,4])
print(type(a))     ## numpy.ndarray
b = [1 , 2,2,3]
print(type(b))       ## list

<class 'numpy.ndarray'>
<class 'list'>


In [19]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [20]:
import numpy as np

arr = np.array([1, 2, 3])       # int64 by default
print(arr.dtype)                 # int64

new_arr = arr.astype(float)     # convert to float
print(new_arr)                   # [1. 2. 3.]
print(new_arr.dtype)             # float64

int64
[1. 2. 3.]
float64


In [ ]:
arr = np.array([1 ,2 ,3 ,4,6 ,5])

print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.mean())
print(np.median(arr))
print(arr.std())
print(arr.var())
print(arr.argmin())
print(arr.argmax())



6
1
21
3.5
3.5
1.707825127659933
2.9166666666666665
0
4


In [42]:
a = np.array([1 ,2 ,3 ,4])
t= a*5
print(t)

m = a+5
print(m)

d  = a/5
print(d)

s = a//2
print(s)

x = a%2
print(x)


[ 5 10 15 20]
[6 7 8 9]
[0.2 0.4 0.6 0.8]
[0 1 1 2]
[1 0 1 0]
